### ISSUE TITLE
ERROR in src/app/api.service.ts:81:54 - error TS2304: Cannot find name 'smartphone'.

### ISSUE THREAD

**Issue by commentatorboy** [didinj/angular-httpclient-example#2]
Thanks for creating this.
There was an issue when updating, running audit fix and then running ng serve.

> ERROR in src/app/api.service.ts:81:54 - error TS2304: Cannot find name 'smartphone'.

So what I did was to change in line 81 where it says: 
`        catchError(this.handleError('addSmartphone', smartphone))`
to
`        catchError(this.handleError('addSmartphone', id))`

If you want I can create a PR.

**Comment by didinj** [comment]
updated to the latest version
